[build]
  command = "wget https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_extended_0.55.6_Linux-64bit.tar.gz && tar -xzf hugo_extended_0.55.6_Linux-64bit.tar.gz && ./hugo"
  publish = "public" 

[build.environment]
  # Keep this commented out so Netlify ignores the automatic install
  # HUGO_VERSION = "0.55.6"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "wget https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_extended_0.55.6_Linux-64bit.tar.gz && tar -xzf hugo_extended_0.55.6_Linux-64bit.tar.gz && ./hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "wget https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_extended_0.55.6_Linux-64bit.tar.gz && tar -xzf hugo_extended_0.55.6_Linux-64bit.tar.gz && ./hugo --gc --minify -b $DEPLOY_PRIME_URL"